name: "Deploy to NuGet"

on:
  push:
    tags:
      - "v*"

env:
  nuget: "https://api.nuget.org/v3/index.json"
  authors: ArchLeaders
  readme: ./Readme.md
  license: ./License.md
  repo: https://github.com/ArchLeaders/Entish
  spdx: MIT
  tags: binary;io;zero-allocation;endian

jobs:
  deploy:
    name: Deploy to NuGet
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Entish
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.x.x"
      
      - name: Restore
        shell: bash
        run: |-
          dotnet restore src/${{ matrix.config.name }}/${{ matrix.config.name }}.csproj
      
      - name: Build
        shell: bash
        run: |-
          dotnet build src/${{ matrix.config.name }}/${{ matrix.config.name }}.csproj \
          --no-restore                                                            \
          -c Release                                                              \
      
      - name: Fetch Version
        id: version
        uses: battila7/get-version-action@v2
      
      - name: Package
        shell: bash
        run: |
          dotnet pack src/${{ matrix.config.name }}/${{ matrix.config.name }}.csproj \
          --no-restore                                                           \
          -c Release                                                             \
          -o ./build-output/                                                     \
          -p:Authors="${{ env.authors }}"                                        \
          -p:PackageLicenseExpression="${{ env.spdx }}"                          \
          -p:PackageLicenseExpression="${{ env.license }}"                       \
          -p:PackageProjectUrl="${{ env.repo }}"                                 \
          -p:PackageReadmeFile="${{ env.readme }}"                               \
          -p:PackageTags='"${{ env.tags }}"'                                     \
          -p:PackageVersion="${{ steps.version.outputs.version-without-v }}"     \
          -p:RepositoryUrl="${{ env.repo }}"                                     \
      
      - name: Push
        shell: bash
        run: |-
          dotnet nuget push ./build-output/*.nupkg \
          -k ${{ secrets.NUGET_AUTH }}             \
          -s ${{ env.nuget }}                      \